# FortiGate 6.4.6 – Práctica P1
# Diomedes Mateo Alvarez – 20250873

config system interface
    edit "port1"                    # WAN – hacia ISP
        set mode static
        set ip 203.0.113.2 255.255.255.252
        set allowaccess ping https ssh http
    next
    edit "port2"                    # LAN – hacia Switch1 (áreas ADMIN/USER/DB)
        set mode static
        set ip 192.168.10.1 255.255.255.0
        set allowaccess ping https ssh http
    next
end

config firewall policy
    edit 1
        set name "LAN_to_internet"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 2
        set name "LAN_to_branch"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
    next
end

config firewall address
    edit "ADMIN"
        set subnet 192.168.10.10 255.255.255.255
    next
    edit "USER"
        set subnet 192.168.10.20 255.255.255.255
    next
    edit "DB"
        set subnet 192.168.10.30 255.255.255.255
    next
end
